#!/usr/bin/env bash

# Make an operating system ready for development.

./create-symlinks
cd this/setup
./create-key-pair
./upload-public-key-to-github

# Introduce myself to git.
if [ -e ~/.gitconfig ]; then
    echo "~/.gitconfig already exists. Not copying: this/dotfiles/gitconfig"
else
    cp -i ../dotfiles/gitconfig ~/.gitconfig
    sensible-editor ~/.gitconfig
fi

# Some operating systems want you to be root.
if [ $(uname -s) = "Darwin" ]; then
    ./install-essentials
else
    sudo ./install-essentials
fi
# Some install scripts want you to be you (not root).
./install-git-completion
./install-git-remote-hg
./install-rvm

[ -x tweak-ui ] && ./tweak-ui
