#!/usr/bin/env bash

if [ -z $(which brew) ]; then
    echo "fatal: Homebrew is not installed." >&2
    echo "visit: http://brew.sh" >&2
    exit 1
fi

echo "See: https://github.com/Homebrew/homebrew-php"
echo "and: https://getcomposer.org/doc/00-intro.md"
brew update
brew tap josegonzalez/homebrew-php
brew tap homebrew/versions
brew install php55-intl
brew install josegonzalez/php/composer

exit $?
