#!/usr/bin/env bash

if [ -z $(which brew) ]; then
    echo "fatal: Homebrew not installed"
    echo "visit: http://brew.sh"
    exit 1
fi

if [ ! -z $(brew cask 2>/dev/null) ] && [ "$1" != "-f" ]; then
    echo "brew cask appears to already be installed"
    echo "Use \"$0 -f\" to force installation."
    exit 2
fi

echo "Info: http://caskroom.io"
brew install caskroom/cask/brew-cask
