#!/usr/bin/env bash

#sudo ./remove-macports
./install-homebrew

for pkg in $(cat essential-cmds.txt); do
    brew install "$pkg"
done
for pkg in $(cat essential-apps.txt); do
    brew cask install "$pkg"
done

./install-php
sudo ./install-pip
sudo ./install-laravel
