#!/usr/bin/env bash

p1=x
p2=y

until [ "$p1" == "$p2" ]; do
    read -p "Set the root password: " -s p1; echo
    read -p "Confirm root password: " -s p2; echo
    if [ "$p1" != "$p2" ]; then
        echo "Passwords do not match. Please try again."
    fi
done
/usr/local/bin/mysqladmin -u root password '$p1'
