#!/usr/bin/env bash

if [ ! -z $(which rvm) ] && [ "$1" != "-f" ]; then
    echo "rvm appears to already be installed." >&2
    echo "Use \"$0 -f\" to force installation." >&2
    exit 1
fi

echo "Info: https://rvm.io/"
\curl -sSL https://get.rvm.io | bash -s stable --rails
