#!/usr/bin/env bash

if [ ! -z $(which composer) ] && [ "$1" != "-f" ]; then
    echo "composer appears to already be installed." >&2
    echo "Use \"$0 -f\" to force installation." >&2
    exit 1
fi

if [ $UID -ne 0 ]; then
    echo "fatal: This script must be run as root" >&2
    echo "usage: sudo $0 $*" >&2
    exit 1
fi

# Check dependencies.
if [ -z $(which php) ]; then
    echo "fatal: PHP is not installed" >&2
    exit 2
fi

echo "Installing Composer, a dependency manager for PHP."
echo "See: https://getcomposer.org/"

download_to="/tmp/composer-installer"
install_to="/usr/local/bin"

if [ ! -z $(which curl) ]; then
    curl -sS https://getcomposer.org/installer > "$download_to"
else
    php -r "readfile('https://getcomposer.org/installer');" > "$download_to"
fi

cat "$download_to" | php -- --install-dir="$install_to"
mv -i "$install_to/composer.phar" "$install_to/composer"
