#!/usr/bin/env bash

if [ $UID -ne 0 ]; then
    echo "fatal: This script must be run as root." >&2
    echo "usage: sudo $0" >&2
    exit 1
fi

apt-get install $(cat essentials.txt)

./install-kernel-dependencies
./install-php
./install-composer
./install-laravel
