#!/usr/bin/env bash

# Turn on numlock at boot.
gsettings set org.gnome.settings-daemon.peripherals.keyboard remember-numlock-state true

# Turn off blinking cursors.
gsettings set org.gnome.desktop.interface cursor-blink false

# Turn off the terminal bell.
if [ ! -z "$(grep "set bell-style none" /etc/inputrc | grep \#)" ]; then
    sudo perl -pi -w -e 's/^(# ?)(set bell-style none)$/$2/g' /etc/inputrc
fi
